name: amd
version: 0.3.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A set of routines for ordering a sparse matrix prior to Cholesky factorization.
homepage: https://github.com/rwl/amd
dependencies:
  logging: '>=0.9.2 <0.10.0'
dev_dependencies:
  unittest: '>=0.11.0+3 <0.12.0'
