name: amd
version: 0.2.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A set of routines for ordering a sparse matrix prior to Cholesky factorization.
homepage: http://www.cise.ufl.edu/research/sparse/amd/
dependencies:
  unittest: '>=0.11.0+3 <0.12.0'
